# Generated by Django 4.1.7 on 2023-05-14 22:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_massages_replay_massages_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="massages",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=blog.models.user_directory_path
            ),
        ),
    ]
